services:
  mototwist:
    image: ghcr.io/amot-dev/mototwist:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mariadb:lts
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql

volumes:
  db: