services:
  mototwist:
    build: .
    environment:
      MYSQL_DATABASE: "mototwist"
      MYSQL_USER: "mototwist"
      MYSQL_PASSWORD: "changethis"
      MYSQL_ROOT_PASSWORD: "changethis"
    volumes:
      - gpx:/gpx
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mariadb:lts
    environment:
      MYSQL_DATABASE: "mototwist"
      MYSQL_USER: "mototwist"
      MYSQL_PASSWORD: "changethis"
      MYSQL_ROOT_PASSWORD: "changethis"
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  gpx:
  mariadb: