services:
  mototwist:
    image: ghcr.io/amot-dev/mototwist:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_healthy

  db:
    image: postgis/postgis:18-3.6
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db: