services:
  mototwist:
    build: .
    env_file:
      - .env
    volumes:
      - gpx:/gpx
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mariadb:lts
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  gpx:
  mariadb: