"""Initial migration for PostgreSQL

Revision ID: 1dc9a4e627cc
Revises: 
Create Date: 2025-09-15 22:27:19.273857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dc9a4e627cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_paved', sa.Boolean(), nullable=False),
    sa.Column('waypoints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('route_geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twists_id'), 'twists', ['id'], unique=False)
    op.create_index(op.f('ix_twists_name'), 'twists', ['name'], unique=False)
    op.create_table('paved_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating_date', sa.Date(), nullable=True),
    sa.Column('traffic', sa.Integer(), nullable=True),
    sa.Column('scenery', sa.Integer(), nullable=True),
    sa.Column('pavement', sa.Integer(), nullable=True),
    sa.Column('twistyness', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('twist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['twist_id'], ['twists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unpaved_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating_date', sa.Date(), nullable=True),
    sa.Column('traffic', sa.Integer(), nullable=True),
    sa.Column('scenery', sa.Integer(), nullable=True),
    sa.Column('surface_consistency', sa.Integer(), nullable=True),
    sa.Column('technicality', sa.Integer(), nullable=True),
    sa.Column('flow', sa.Integer(), nullable=True),
    sa.Column('twist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['twist_id'], ['twists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unpaved_ratings')
    op.drop_table('paved_ratings')
    op.drop_index(op.f('ix_twists_name'), table_name='twists')
    op.drop_index(op.f('ix_twists_id'), table_name='twists')
    op.drop_table('twists')
    # ### end Alembic commands ###
