"""Cascade delete Ratings

Revision ID: bfe157cf81cb
Revises: 1dc9a4e627cc
Create Date: 2025-09-16 07:05:50.557815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe157cf81cb'
down_revision: Union[str, Sequence[str], None] = '1dc9a4e627cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('paved_ratings_twist_id_fkey'), 'paved_ratings', type_='foreignkey')
    op.create_foreign_key(None, 'paved_ratings', 'twists', ['twist_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('unpaved_ratings_twist_id_fkey'), 'unpaved_ratings', type_='foreignkey')
    op.create_foreign_key(None, 'unpaved_ratings', 'twists', ['twist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unpaved_ratings', type_='foreignkey')
    op.create_foreign_key(op.f('unpaved_ratings_twist_id_fkey'), 'unpaved_ratings', 'twists', ['twist_id'], ['id'])
    op.drop_constraint(None, 'paved_ratings', type_='foreignkey')
    op.create_foreign_key(op.f('paved_ratings_twist_id_fkey'), 'paved_ratings', 'twists', ['twist_id'], ['id'])
    # ### end Alembic commands ###
