"""Add ownership

Revision ID: e8c5c0ec59cb
Revises: a773686af18b
Create Date: 2025-10-11 04:54:55.005826

"""
from typing import Sequence, Union
from fastapi_users_db_sqlalchemy.generics import GUID

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8c5c0ec59cb'
down_revision: Union[str, Sequence[str], None] = 'a773686af18b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paved_ratings', sa.Column('author_id', GUID(), nullable=False))
    op.create_foreign_key(None, 'paved_ratings', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.add_column('twists', sa.Column('author_id', GUID(), nullable=False))
    op.create_foreign_key(None, 'twists', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.add_column('unpaved_ratings', sa.Column('author_id', GUID(), nullable=False))
    op.create_foreign_key(None, 'unpaved_ratings', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unpaved_ratings', type_='foreignkey')
    op.drop_column('unpaved_ratings', 'author_id')
    op.drop_constraint(None, 'twists', type_='foreignkey')
    op.drop_column('twists', 'author_id')
    op.drop_constraint(None, 'paved_ratings', type_='foreignkey')
    op.drop_column('paved_ratings', 'author_id')
    # ### end Alembic commands ###
