"""Add users

Revision ID: 75cf8bd4f3f8
Revises: 041e9b3d45d1
Create Date: 2025-09-17 22:35:25.356610

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75cf8bd4f3f8'
down_revision: Union[str, Sequence[str], None] = '041e9b3d45d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('paved_ratings', 'rating_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('paved_ratings', 'traffic',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('paved_ratings', 'scenery',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('paved_ratings', 'pavement',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('paved_ratings', 'twistyness',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('paved_ratings', 'intensity',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('paved_ratings', 'twist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('twists', 'simplification_tolerance_m',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('unpaved_ratings', 'rating_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('unpaved_ratings', 'traffic',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('unpaved_ratings', 'scenery',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('unpaved_ratings', 'surface_consistency',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('unpaved_ratings', 'technicality',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('unpaved_ratings', 'flow',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('unpaved_ratings', 'twist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unpaved_ratings', 'twist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('unpaved_ratings', 'flow',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('unpaved_ratings', 'technicality',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('unpaved_ratings', 'surface_consistency',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('unpaved_ratings', 'scenery',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('unpaved_ratings', 'traffic',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('unpaved_ratings', 'rating_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('twists', 'simplification_tolerance_m',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('paved_ratings', 'twist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('paved_ratings', 'intensity',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('paved_ratings', 'twistyness',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('paved_ratings', 'pavement',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('paved_ratings', 'scenery',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('paved_ratings', 'traffic',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('paved_ratings', 'rating_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
