"""Soften user deletion

Revision ID: c67e3d6098e1
Revises: e8c5c0ec59cb
Create Date: 2025-10-17 08:03:48.997319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67e3d6098e1'
down_revision: Union[str, Sequence[str], None] = 'e8c5c0ec59cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paved_ratings', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('paved_ratings_author_id_fkey'), 'paved_ratings', type_='foreignkey')
    op.create_foreign_key(None, 'paved_ratings', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.alter_column('twists', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('twists_author_id_fkey'), 'twists', type_='foreignkey')
    op.create_foreign_key(None, 'twists', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.alter_column('unpaved_ratings', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('unpaved_ratings_author_id_fkey'), 'unpaved_ratings', type_='foreignkey')
    op.create_foreign_key(None, 'unpaved_ratings', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unpaved_ratings', type_='foreignkey')
    op.create_foreign_key(op.f('unpaved_ratings_author_id_fkey'), 'unpaved_ratings', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.alter_column('unpaved_ratings', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'twists', type_='foreignkey')
    op.create_foreign_key(op.f('twists_author_id_fkey'), 'twists', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.alter_column('twists', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'paved_ratings', type_='foreignkey')
    op.create_foreign_key(op.f('paved_ratings_author_id_fkey'), 'paved_ratings', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.alter_column('paved_ratings', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
