"""Add simplification tolerance to twists

Revision ID: 23c739ab87f6
Revises: bfe157cf81cb
Create Date: 2025-09-17 00:41:31.415908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c739ab87f6'
down_revision: Union[str, Sequence[str], None] = 'bfe157cf81cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twists', sa.Column('simplification_tolerance_m', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twists', 'simplification_tolerance_m')
    # ### end Alembic commands ###
