"""Move away from GPX

Revision ID: 303db2758fd3
Revises: 5e760d528ebb
Create Date: 2025-09-15 07:53:54.901850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '303db2758fd3'
down_revision: Union[str, Sequence[str], None] = '5e760d528ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twists', sa.Column('waypoints', sa.JSON(), nullable=False))
    op.add_column('twists', sa.Column('route_geometry', sa.JSON(), nullable=False))
    op.drop_index(op.f('file_path'), table_name='twists')
    op.drop_column('twists', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twists', sa.Column('file_path', mysql.VARCHAR(length=255), nullable=False))
    op.create_index(op.f('file_path'), 'twists', ['file_path'], unique=True)
    op.drop_column('twists', 'route_geometry')
    op.drop_column('twists', 'waypoints')
    # ### end Alembic commands ###
