"""Initial

Revision ID: 4c0c52436fb4
Revises: 
Create Date: 2025-09-08 00:44:09.721250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0c52436fb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('is_paved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_twists_id'), 'twists', ['id'], unique=False)
    op.create_index(op.f('ix_twists_name'), 'twists', ['name'], unique=False)
    op.create_table('paved_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating_date', sa.Date(), nullable=True),
    sa.Column('smoothness', sa.Integer(), nullable=True),
    sa.Column('scenery', sa.Integer(), nullable=True),
    sa.Column('twist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['twist_id'], ['twists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unpaved_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating_date', sa.Date(), nullable=True),
    sa.Column('technicality', sa.Integer(), nullable=True),
    sa.Column('flow', sa.Integer(), nullable=True),
    sa.Column('twist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['twist_id'], ['twists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unpaved_ratings')
    op.drop_table('paved_ratings')
    op.drop_index(op.f('ix_twists_name'), table_name='twists')
    op.drop_index(op.f('ix_twists_id'), table_name='twists')
    op.drop_table('twists')
    # ### end Alembic commands ###
