name: Deploy Docs
run-name: Deploy Docs for ${{ github.ref_name }}

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

jobs:
  deploy-docs:
    uses: amot-dev/actions/.github/workflows/deploy-docs.yml@v1
