name: Docker Build to GHCR
run-name: Build version ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    tags:
      - 'v*'

jobs:
  build-ghcr:
    uses: amot-dev/actions/.github/workflows/ghcr.yml@v1
    with:
      build_args: |
        MOTOTWIST_VERSION=${{ github.ref_name }}
